// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Punchclock.Web.Data;

namespace Punchclock.Web.Migrations
{
    [DbContext(typeof(PunchclockContext))]
    [Migration("20191104215626_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Punchclock.Web.Data.Entities.Department", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Title = "Department 1"
                        },
                        new
                        {
                            Id = 2L,
                            Title = "Department 2"
                        },
                        new
                        {
                            Id = 3L,
                            Title = "Department 3"
                        },
                        new
                        {
                            Id = 4L,
                            Title = "Department 4"
                        },
                        new
                        {
                            Id = 5L,
                            Title = "Department 5"
                        },
                        new
                        {
                            Id = 6L,
                            Title = "Department 6"
                        });
                });

            modelBuilder.Entity("Punchclock.Web.Data.Entities.Entry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Entries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CheckIn = new DateTime(2019, 11, 3, 22, 56, 26, 291, DateTimeKind.Local).AddTicks(9297),
                            CheckOut = new DateTime(2019, 11, 5, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(795),
                            EmployeeId = "13"
                        },
                        new
                        {
                            Id = 2L,
                            CheckIn = new DateTime(2019, 11, 2, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1652),
                            CheckOut = new DateTime(2019, 11, 6, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1668),
                            EmployeeId = "4"
                        },
                        new
                        {
                            Id = 3L,
                            CheckIn = new DateTime(2019, 11, 1, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1694),
                            CheckOut = new DateTime(2019, 11, 7, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1696),
                            EmployeeId = "7"
                        },
                        new
                        {
                            Id = 4L,
                            CheckIn = new DateTime(2019, 10, 31, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1699),
                            CheckOut = new DateTime(2019, 11, 8, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1700),
                            EmployeeId = "11"
                        },
                        new
                        {
                            Id = 5L,
                            CheckIn = new DateTime(2019, 10, 30, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1703),
                            CheckOut = new DateTime(2019, 11, 9, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1705),
                            EmployeeId = "3"
                        },
                        new
                        {
                            Id = 6L,
                            CheckIn = new DateTime(2019, 10, 29, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1707),
                            CheckOut = new DateTime(2019, 11, 10, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1708),
                            EmployeeId = "5"
                        },
                        new
                        {
                            Id = 7L,
                            CheckIn = new DateTime(2019, 10, 28, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1710),
                            CheckOut = new DateTime(2019, 11, 11, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1712),
                            EmployeeId = "11"
                        },
                        new
                        {
                            Id = 8L,
                            CheckIn = new DateTime(2019, 10, 27, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1714),
                            CheckOut = new DateTime(2019, 11, 12, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1715),
                            EmployeeId = "4"
                        },
                        new
                        {
                            Id = 9L,
                            CheckIn = new DateTime(2019, 10, 26, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1718),
                            CheckOut = new DateTime(2019, 11, 13, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1719),
                            EmployeeId = "11"
                        },
                        new
                        {
                            Id = 10L,
                            CheckIn = new DateTime(2019, 10, 25, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1721),
                            CheckOut = new DateTime(2019, 11, 14, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1723),
                            EmployeeId = "11"
                        },
                        new
                        {
                            Id = 11L,
                            CheckIn = new DateTime(2019, 10, 24, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1725),
                            CheckOut = new DateTime(2019, 11, 15, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1726),
                            EmployeeId = "9"
                        },
                        new
                        {
                            Id = 12L,
                            CheckIn = new DateTime(2019, 10, 23, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1766),
                            CheckOut = new DateTime(2019, 11, 16, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1768),
                            EmployeeId = "14"
                        },
                        new
                        {
                            Id = 13L,
                            CheckIn = new DateTime(2019, 10, 22, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1771),
                            CheckOut = new DateTime(2019, 11, 17, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1772),
                            EmployeeId = "10"
                        },
                        new
                        {
                            Id = 14L,
                            CheckIn = new DateTime(2019, 10, 21, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1775),
                            CheckOut = new DateTime(2019, 11, 18, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1776),
                            EmployeeId = "11"
                        },
                        new
                        {
                            Id = 15L,
                            CheckIn = new DateTime(2019, 10, 20, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1778),
                            CheckOut = new DateTime(2019, 11, 19, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1780),
                            EmployeeId = "20"
                        },
                        new
                        {
                            Id = 16L,
                            CheckIn = new DateTime(2019, 10, 19, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1782),
                            CheckOut = new DateTime(2019, 11, 20, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1783),
                            EmployeeId = "15"
                        },
                        new
                        {
                            Id = 17L,
                            CheckIn = new DateTime(2019, 10, 18, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1785),
                            CheckOut = new DateTime(2019, 11, 21, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1787),
                            EmployeeId = "19"
                        },
                        new
                        {
                            Id = 18L,
                            CheckIn = new DateTime(2019, 10, 17, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1789),
                            CheckOut = new DateTime(2019, 11, 22, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1790),
                            EmployeeId = "14"
                        },
                        new
                        {
                            Id = 19L,
                            CheckIn = new DateTime(2019, 10, 16, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1792),
                            CheckOut = new DateTime(2019, 11, 23, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1794),
                            EmployeeId = "8"
                        },
                        new
                        {
                            Id = 20L,
                            CheckIn = new DateTime(2019, 10, 15, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1796),
                            CheckOut = new DateTime(2019, 11, 24, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1797),
                            EmployeeId = "1"
                        },
                        new
                        {
                            Id = 21L,
                            CheckIn = new DateTime(2019, 10, 14, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1799),
                            CheckOut = new DateTime(2019, 11, 25, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1801),
                            EmployeeId = "2"
                        },
                        new
                        {
                            Id = 22L,
                            CheckIn = new DateTime(2019, 10, 13, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1803),
                            CheckOut = new DateTime(2019, 11, 26, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1804),
                            EmployeeId = "5"
                        },
                        new
                        {
                            Id = 23L,
                            CheckIn = new DateTime(2019, 10, 12, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1806),
                            CheckOut = new DateTime(2019, 11, 27, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1808),
                            EmployeeId = "18"
                        },
                        new
                        {
                            Id = 24L,
                            CheckIn = new DateTime(2019, 10, 11, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1810),
                            CheckOut = new DateTime(2019, 11, 28, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1812),
                            EmployeeId = "1"
                        },
                        new
                        {
                            Id = 25L,
                            CheckIn = new DateTime(2019, 10, 10, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1813),
                            CheckOut = new DateTime(2019, 11, 29, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1815),
                            EmployeeId = "2"
                        },
                        new
                        {
                            Id = 26L,
                            CheckIn = new DateTime(2019, 10, 9, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1817),
                            CheckOut = new DateTime(2019, 11, 30, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1818),
                            EmployeeId = "4"
                        },
                        new
                        {
                            Id = 27L,
                            CheckIn = new DateTime(2019, 10, 8, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1820),
                            CheckOut = new DateTime(2019, 12, 1, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1821),
                            EmployeeId = "14"
                        },
                        new
                        {
                            Id = 28L,
                            CheckIn = new DateTime(2019, 10, 7, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1823),
                            CheckOut = new DateTime(2019, 12, 2, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1825),
                            EmployeeId = "15"
                        },
                        new
                        {
                            Id = 29L,
                            CheckIn = new DateTime(2019, 10, 6, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1827),
                            CheckOut = new DateTime(2019, 12, 3, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1828),
                            EmployeeId = "18"
                        },
                        new
                        {
                            Id = 30L,
                            CheckIn = new DateTime(2019, 10, 5, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1830),
                            CheckOut = new DateTime(2019, 12, 4, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1832),
                            EmployeeId = "20"
                        },
                        new
                        {
                            Id = 31L,
                            CheckIn = new DateTime(2019, 10, 4, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1834),
                            CheckOut = new DateTime(2019, 12, 5, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1835),
                            EmployeeId = "4"
                        },
                        new
                        {
                            Id = 32L,
                            CheckIn = new DateTime(2019, 10, 3, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1837),
                            CheckOut = new DateTime(2019, 12, 6, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1838),
                            EmployeeId = "4"
                        },
                        new
                        {
                            Id = 33L,
                            CheckIn = new DateTime(2019, 10, 2, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1840),
                            CheckOut = new DateTime(2019, 12, 7, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1842),
                            EmployeeId = "17"
                        },
                        new
                        {
                            Id = 34L,
                            CheckIn = new DateTime(2019, 10, 1, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1844),
                            CheckOut = new DateTime(2019, 12, 8, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1845),
                            EmployeeId = "12"
                        },
                        new
                        {
                            Id = 35L,
                            CheckIn = new DateTime(2019, 9, 30, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1848),
                            CheckOut = new DateTime(2019, 12, 9, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1849),
                            EmployeeId = "18"
                        },
                        new
                        {
                            Id = 36L,
                            CheckIn = new DateTime(2019, 9, 29, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1851),
                            CheckOut = new DateTime(2019, 12, 10, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1853),
                            EmployeeId = "15"
                        },
                        new
                        {
                            Id = 37L,
                            CheckIn = new DateTime(2019, 9, 28, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1855),
                            CheckOut = new DateTime(2019, 12, 11, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1856),
                            EmployeeId = "7"
                        },
                        new
                        {
                            Id = 38L,
                            CheckIn = new DateTime(2019, 9, 27, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1859),
                            CheckOut = new DateTime(2019, 12, 12, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1860),
                            EmployeeId = "16"
                        },
                        new
                        {
                            Id = 39L,
                            CheckIn = new DateTime(2019, 9, 26, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1862),
                            CheckOut = new DateTime(2019, 12, 13, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1863),
                            EmployeeId = "14"
                        },
                        new
                        {
                            Id = 40L,
                            CheckIn = new DateTime(2019, 9, 25, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1866),
                            CheckOut = new DateTime(2019, 12, 14, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1867),
                            EmployeeId = "15"
                        },
                        new
                        {
                            Id = 41L,
                            CheckIn = new DateTime(2019, 9, 24, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1869),
                            CheckOut = new DateTime(2019, 12, 15, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1871),
                            EmployeeId = "2"
                        },
                        new
                        {
                            Id = 42L,
                            CheckIn = new DateTime(2019, 9, 23, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1872),
                            CheckOut = new DateTime(2019, 12, 16, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1874),
                            EmployeeId = "13"
                        },
                        new
                        {
                            Id = 43L,
                            CheckIn = new DateTime(2019, 9, 22, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1876),
                            CheckOut = new DateTime(2019, 12, 17, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1878),
                            EmployeeId = "12"
                        },
                        new
                        {
                            Id = 44L,
                            CheckIn = new DateTime(2019, 9, 21, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1880),
                            CheckOut = new DateTime(2019, 12, 18, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1881),
                            EmployeeId = "18"
                        },
                        new
                        {
                            Id = 45L,
                            CheckIn = new DateTime(2019, 9, 20, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1883),
                            CheckOut = new DateTime(2019, 12, 19, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1885),
                            EmployeeId = "2"
                        },
                        new
                        {
                            Id = 46L,
                            CheckIn = new DateTime(2019, 9, 19, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1887),
                            CheckOut = new DateTime(2019, 12, 20, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1888),
                            EmployeeId = "16"
                        },
                        new
                        {
                            Id = 47L,
                            CheckIn = new DateTime(2019, 9, 18, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1890),
                            CheckOut = new DateTime(2019, 12, 21, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1892),
                            EmployeeId = "15"
                        },
                        new
                        {
                            Id = 48L,
                            CheckIn = new DateTime(2019, 9, 17, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1894),
                            CheckOut = new DateTime(2019, 12, 22, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1895),
                            EmployeeId = "15"
                        },
                        new
                        {
                            Id = 49L,
                            CheckIn = new DateTime(2019, 9, 16, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1897),
                            CheckOut = new DateTime(2019, 12, 23, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1899),
                            EmployeeId = "4"
                        },
                        new
                        {
                            Id = 50L,
                            CheckIn = new DateTime(2019, 9, 15, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1901),
                            CheckOut = new DateTime(2019, 12, 24, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1902),
                            EmployeeId = "18"
                        },
                        new
                        {
                            Id = 51L,
                            CheckIn = new DateTime(2019, 9, 14, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1904),
                            CheckOut = new DateTime(2019, 12, 25, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1906),
                            EmployeeId = "16"
                        },
                        new
                        {
                            Id = 52L,
                            CheckIn = new DateTime(2019, 9, 13, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1908),
                            CheckOut = new DateTime(2019, 12, 26, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1909),
                            EmployeeId = "18"
                        },
                        new
                        {
                            Id = 53L,
                            CheckIn = new DateTime(2019, 9, 12, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1911),
                            CheckOut = new DateTime(2019, 12, 27, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1912),
                            EmployeeId = "20"
                        },
                        new
                        {
                            Id = 54L,
                            CheckIn = new DateTime(2019, 9, 11, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1914),
                            CheckOut = new DateTime(2019, 12, 28, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1916),
                            EmployeeId = "16"
                        },
                        new
                        {
                            Id = 55L,
                            CheckIn = new DateTime(2019, 9, 10, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1918),
                            CheckOut = new DateTime(2019, 12, 29, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1919),
                            EmployeeId = "8"
                        },
                        new
                        {
                            Id = 56L,
                            CheckIn = new DateTime(2019, 9, 9, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1921),
                            CheckOut = new DateTime(2019, 12, 30, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1922),
                            EmployeeId = "8"
                        },
                        new
                        {
                            Id = 57L,
                            CheckIn = new DateTime(2019, 9, 8, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1924),
                            CheckOut = new DateTime(2019, 12, 31, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1926),
                            EmployeeId = "7"
                        },
                        new
                        {
                            Id = 58L,
                            CheckIn = new DateTime(2019, 9, 7, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1928),
                            CheckOut = new DateTime(2020, 1, 1, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1929),
                            EmployeeId = "6"
                        },
                        new
                        {
                            Id = 59L,
                            CheckIn = new DateTime(2019, 9, 6, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1931),
                            CheckOut = new DateTime(2020, 1, 2, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1933),
                            EmployeeId = "10"
                        },
                        new
                        {
                            Id = 60L,
                            CheckIn = new DateTime(2019, 9, 5, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1935),
                            CheckOut = new DateTime(2020, 1, 3, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1936),
                            EmployeeId = "20"
                        },
                        new
                        {
                            Id = 61L,
                            CheckIn = new DateTime(2019, 9, 4, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1938),
                            CheckOut = new DateTime(2020, 1, 4, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1940),
                            EmployeeId = "12"
                        },
                        new
                        {
                            Id = 62L,
                            CheckIn = new DateTime(2019, 9, 3, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1942),
                            CheckOut = new DateTime(2020, 1, 5, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1943),
                            EmployeeId = "16"
                        },
                        new
                        {
                            Id = 63L,
                            CheckIn = new DateTime(2019, 9, 2, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1945),
                            CheckOut = new DateTime(2020, 1, 6, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1947),
                            EmployeeId = "6"
                        },
                        new
                        {
                            Id = 64L,
                            CheckIn = new DateTime(2019, 9, 1, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1949),
                            CheckOut = new DateTime(2020, 1, 7, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1950),
                            EmployeeId = "12"
                        },
                        new
                        {
                            Id = 65L,
                            CheckIn = new DateTime(2019, 8, 31, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1952),
                            CheckOut = new DateTime(2020, 1, 8, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1954),
                            EmployeeId = "8"
                        },
                        new
                        {
                            Id = 66L,
                            CheckIn = new DateTime(2019, 8, 30, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1956),
                            CheckOut = new DateTime(2020, 1, 9, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1957),
                            EmployeeId = "5"
                        },
                        new
                        {
                            Id = 67L,
                            CheckIn = new DateTime(2019, 8, 29, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1959),
                            CheckOut = new DateTime(2020, 1, 10, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1961),
                            EmployeeId = "18"
                        },
                        new
                        {
                            Id = 68L,
                            CheckIn = new DateTime(2019, 8, 28, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1963),
                            CheckOut = new DateTime(2020, 1, 11, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1964),
                            EmployeeId = "18"
                        },
                        new
                        {
                            Id = 69L,
                            CheckIn = new DateTime(2019, 8, 27, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1966),
                            CheckOut = new DateTime(2020, 1, 12, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1968),
                            EmployeeId = "13"
                        },
                        new
                        {
                            Id = 70L,
                            CheckIn = new DateTime(2019, 8, 26, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1970),
                            CheckOut = new DateTime(2020, 1, 13, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1971),
                            EmployeeId = "5"
                        },
                        new
                        {
                            Id = 71L,
                            CheckIn = new DateTime(2019, 8, 25, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1973),
                            CheckOut = new DateTime(2020, 1, 14, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1975),
                            EmployeeId = "9"
                        },
                        new
                        {
                            Id = 72L,
                            CheckIn = new DateTime(2019, 8, 24, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1977),
                            CheckOut = new DateTime(2020, 1, 15, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(1978),
                            EmployeeId = "4"
                        },
                        new
                        {
                            Id = 73L,
                            CheckIn = new DateTime(2019, 8, 23, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2106),
                            CheckOut = new DateTime(2020, 1, 16, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2107),
                            EmployeeId = "1"
                        },
                        new
                        {
                            Id = 74L,
                            CheckIn = new DateTime(2019, 8, 22, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2109),
                            CheckOut = new DateTime(2020, 1, 17, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2111),
                            EmployeeId = "14"
                        },
                        new
                        {
                            Id = 75L,
                            CheckIn = new DateTime(2019, 8, 21, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2113),
                            CheckOut = new DateTime(2020, 1, 18, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2115),
                            EmployeeId = "20"
                        },
                        new
                        {
                            Id = 76L,
                            CheckIn = new DateTime(2019, 8, 20, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2117),
                            CheckOut = new DateTime(2020, 1, 19, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2118),
                            EmployeeId = "10"
                        },
                        new
                        {
                            Id = 77L,
                            CheckIn = new DateTime(2019, 8, 19, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2120),
                            CheckOut = new DateTime(2020, 1, 20, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2122),
                            EmployeeId = "14"
                        },
                        new
                        {
                            Id = 78L,
                            CheckIn = new DateTime(2019, 8, 18, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2124),
                            CheckOut = new DateTime(2020, 1, 21, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2125),
                            EmployeeId = "20"
                        },
                        new
                        {
                            Id = 79L,
                            CheckIn = new DateTime(2019, 8, 17, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2128),
                            CheckOut = new DateTime(2020, 1, 22, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2129),
                            EmployeeId = "20"
                        },
                        new
                        {
                            Id = 80L,
                            CheckIn = new DateTime(2019, 8, 16, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2131),
                            CheckOut = new DateTime(2020, 1, 23, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2132),
                            EmployeeId = "7"
                        },
                        new
                        {
                            Id = 81L,
                            CheckIn = new DateTime(2019, 8, 15, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2134),
                            CheckOut = new DateTime(2020, 1, 24, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2136),
                            EmployeeId = "9"
                        },
                        new
                        {
                            Id = 82L,
                            CheckIn = new DateTime(2019, 8, 14, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2138),
                            CheckOut = new DateTime(2020, 1, 25, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2140),
                            EmployeeId = "20"
                        },
                        new
                        {
                            Id = 83L,
                            CheckIn = new DateTime(2019, 8, 13, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2142),
                            CheckOut = new DateTime(2020, 1, 26, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2143),
                            EmployeeId = "12"
                        },
                        new
                        {
                            Id = 84L,
                            CheckIn = new DateTime(2019, 8, 12, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2145),
                            CheckOut = new DateTime(2020, 1, 27, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2147),
                            EmployeeId = "20"
                        },
                        new
                        {
                            Id = 85L,
                            CheckIn = new DateTime(2019, 8, 11, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2149),
                            CheckOut = new DateTime(2020, 1, 28, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2151),
                            EmployeeId = "5"
                        },
                        new
                        {
                            Id = 86L,
                            CheckIn = new DateTime(2019, 8, 10, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2153),
                            CheckOut = new DateTime(2020, 1, 29, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2154),
                            EmployeeId = "7"
                        },
                        new
                        {
                            Id = 87L,
                            CheckIn = new DateTime(2019, 8, 9, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2156),
                            CheckOut = new DateTime(2020, 1, 30, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2158),
                            EmployeeId = "4"
                        },
                        new
                        {
                            Id = 88L,
                            CheckIn = new DateTime(2019, 8, 8, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2160),
                            CheckOut = new DateTime(2020, 1, 31, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2161),
                            EmployeeId = "1"
                        },
                        new
                        {
                            Id = 89L,
                            CheckIn = new DateTime(2019, 8, 7, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2163),
                            CheckOut = new DateTime(2020, 2, 1, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2165),
                            EmployeeId = "5"
                        },
                        new
                        {
                            Id = 90L,
                            CheckIn = new DateTime(2019, 8, 6, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2167),
                            CheckOut = new DateTime(2020, 2, 2, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2168),
                            EmployeeId = "10"
                        },
                        new
                        {
                            Id = 91L,
                            CheckIn = new DateTime(2019, 8, 5, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2170),
                            CheckOut = new DateTime(2020, 2, 3, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2172),
                            EmployeeId = "8"
                        },
                        new
                        {
                            Id = 92L,
                            CheckIn = new DateTime(2019, 8, 4, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2174),
                            CheckOut = new DateTime(2020, 2, 4, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2175),
                            EmployeeId = "1"
                        },
                        new
                        {
                            Id = 93L,
                            CheckIn = new DateTime(2019, 8, 3, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2178),
                            CheckOut = new DateTime(2020, 2, 5, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2179),
                            EmployeeId = "6"
                        },
                        new
                        {
                            Id = 94L,
                            CheckIn = new DateTime(2019, 8, 2, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2181),
                            CheckOut = new DateTime(2020, 2, 6, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2182),
                            EmployeeId = "14"
                        },
                        new
                        {
                            Id = 95L,
                            CheckIn = new DateTime(2019, 8, 1, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2185),
                            CheckOut = new DateTime(2020, 2, 7, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2186),
                            EmployeeId = "3"
                        },
                        new
                        {
                            Id = 96L,
                            CheckIn = new DateTime(2019, 7, 31, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2188),
                            CheckOut = new DateTime(2020, 2, 8, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2189),
                            EmployeeId = "6"
                        },
                        new
                        {
                            Id = 97L,
                            CheckIn = new DateTime(2019, 7, 30, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2192),
                            CheckOut = new DateTime(2020, 2, 9, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2193),
                            EmployeeId = "7"
                        },
                        new
                        {
                            Id = 98L,
                            CheckIn = new DateTime(2019, 7, 29, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2195),
                            CheckOut = new DateTime(2020, 2, 10, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2196),
                            EmployeeId = "1"
                        },
                        new
                        {
                            Id = 99L,
                            CheckIn = new DateTime(2019, 7, 28, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2198),
                            CheckOut = new DateTime(2020, 2, 11, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2200),
                            EmployeeId = "10"
                        },
                        new
                        {
                            Id = 100L,
                            CheckIn = new DateTime(2019, 7, 27, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2202),
                            CheckOut = new DateTime(2020, 2, 12, 22, 56, 26, 296, DateTimeKind.Local).AddTicks(2204),
                            EmployeeId = "17"
                        });
                });

            modelBuilder.Entity("Punchclock.Web.Data.Entities.Employee", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<long>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("DepartmentId");

                    b.HasDiscriminator().HasValue("Employee");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aec81e47-b49a-43f4-be8e-dcec5768434b",
                            Email = "test1@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5aa719f4-c0af-4e3d-9804-0b55325d1bff",
                            TwoFactorEnabled = false,
                            DepartmentId = 6L
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f2e14e8d-4c35-4bc3-adeb-a6c6c9c6cfa9",
                            Email = "test2@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d92efa4e-e62c-49f3-9b0f-6b1c6c392891",
                            TwoFactorEnabled = false,
                            DepartmentId = 4L
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ba0a452f-ddb4-44a0-b616-a25d9f232474",
                            Email = "test3@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "57c58da5-210c-46cf-a297-30c77900504b",
                            TwoFactorEnabled = false,
                            DepartmentId = 2L
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ddd91316-2f96-4596-ba23-108e94042502",
                            Email = "test4@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6016f6b7-1a53-4609-83c5-7e2ab07ff90d",
                            TwoFactorEnabled = false,
                            DepartmentId = 5L
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e2cb5bda-c101-4b6c-b78a-0fd937e00529",
                            Email = "test5@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e3723920-1ad4-422b-94ea-2ec62399e180",
                            TwoFactorEnabled = false,
                            DepartmentId = 6L
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e27faaee-c4e9-449b-b340-daa4b5189f45",
                            Email = "test6@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4d0ee317-7df2-4fa6-8624-25a71ae804db",
                            TwoFactorEnabled = false,
                            DepartmentId = 4L
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0b0fc1a2-aaf2-47cf-805e-f7e90bee9536",
                            Email = "test7@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c363e46b-4878-4ce4-bae2-ae93332d31ad",
                            TwoFactorEnabled = false,
                            DepartmentId = 5L
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ff164abf-6a49-4a14-b505-0bb6ca858f76",
                            Email = "test8@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d9d4b4cd-e7de-45f5-bb34-ad4a3dd70bc8",
                            TwoFactorEnabled = false,
                            DepartmentId = 1L
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "944cb71d-aa7d-4cb2-bee9-b210f93ee4f5",
                            Email = "test9@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "74d57505-0670-4a71-9651-b9727a95a7f8",
                            TwoFactorEnabled = false,
                            DepartmentId = 3L
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2e8c8c33-b0b8-4b91-a1a6-e58e5842b7ee",
                            Email = "test10@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a77571f0-30b2-461e-aed8-94dda18b8504",
                            TwoFactorEnabled = false,
                            DepartmentId = 3L
                        },
                        new
                        {
                            Id = "11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ef0c5e31-fd3f-49d0-a30d-37fa1737217e",
                            Email = "test11@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9e019954-d65c-4fe0-b4bb-b3ebf52071c0",
                            TwoFactorEnabled = false,
                            DepartmentId = 3L
                        },
                        new
                        {
                            Id = "12",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d4e70aeb-f5fc-4ea5-b20c-823f8a370420",
                            Email = "test12@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4e7696bc-c57e-4d1e-9308-cb8144657c35",
                            TwoFactorEnabled = false,
                            DepartmentId = 2L
                        },
                        new
                        {
                            Id = "13",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "40997aa0-ff2b-4417-8c5c-d2b2073450ec",
                            Email = "test13@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "909da6c9-0a91-4d64-a52e-c39d54d7869b",
                            TwoFactorEnabled = false,
                            DepartmentId = 2L
                        },
                        new
                        {
                            Id = "14",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f87129cf-05bf-451b-bfac-712c61f8bbc3",
                            Email = "test14@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3dbd6881-4aaa-43a0-b0db-ac955e4df1d2",
                            TwoFactorEnabled = false,
                            DepartmentId = 1L
                        },
                        new
                        {
                            Id = "15",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0bba95f0-fae2-483f-8034-1b2d087ab3bc",
                            Email = "test15@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a9362a26-6ea9-401d-b3d7-ba0fc95006f2",
                            TwoFactorEnabled = false,
                            DepartmentId = 4L
                        },
                        new
                        {
                            Id = "16",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ba6e804a-2dbc-421d-9331-dff8ee0cb54a",
                            Email = "test16@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f98c8b1b-8c37-4145-a9e7-843aee1cffc1",
                            TwoFactorEnabled = false,
                            DepartmentId = 5L
                        },
                        new
                        {
                            Id = "17",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ae97d17d-c0dd-4d33-9838-c224edbf8570",
                            Email = "test17@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fb98ad7c-843e-42d9-aa3a-7e9310a26052",
                            TwoFactorEnabled = false,
                            DepartmentId = 4L
                        },
                        new
                        {
                            Id = "18",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "47f278e9-0d52-43d5-8b72-fd601f9f6a87",
                            Email = "test18@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13bf1f47-4dca-405d-b950-bc413c9e421a",
                            TwoFactorEnabled = false,
                            DepartmentId = 3L
                        },
                        new
                        {
                            Id = "19",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da964cad-1cb9-4303-b325-eb4937d5751e",
                            Email = "test19@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f7311b23-28d0-4346-a056-4cb0e9337ab5",
                            TwoFactorEnabled = false,
                            DepartmentId = 5L
                        },
                        new
                        {
                            Id = "20",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3f2b6106-cb27-4895-950f-ba18e99e94eb",
                            Email = "test20@test.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6b5ea6e3-8edc-40c9-b1f1-a59e52ca0411",
                            TwoFactorEnabled = false,
                            DepartmentId = 3L
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Punchclock.Web.Data.Entities.Entry", b =>
                {
                    b.HasOne("Punchclock.Web.Data.Entities.Employee", "Employee")
                        .WithMany("Entries")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Punchclock.Web.Data.Entities.Employee", b =>
                {
                    b.HasOne("Punchclock.Web.Data.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
